name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar en Surge
        run: surge ./ https://mi-proyecto.surge.sh --token ${{ secrets.SURGE_TOKEN }}
